### ISSUE TITLE
total number of predicted Rho-dependent terminators

### ISSUE THREAD

**Issue by RB786** [MarcoDiSalvo90/RhoTermPredict#2]
I have different 20 genomic sequences in a single file  and when i am running RhoTermPredict I am getting a output files file (excel - Rho-dependent_terminators_coordinates.xlsx and text - Informations_about_predictions.txt). 
I expected to get the terminator coordinates for each sequence but here I am getting an output with total number of predicted Rho-dependent terminators as 4. Can you please clarify why is this that I am not getting terminator site for eah sequences.

**Comment by MarcoDiSalvo90** [comment]
Hi,

now it was introduced the possibility to analyze more than one genomic sequence saved into the input fasta file, and results will be provided in different files for each sequence.

Regarding your problem, maybe not all the input sequences had predicted RUT sites or, probably, you analyzed only the first sequence of your file, because RhoTermPredict was not able to analyze more than one sequence for run. But now, in this new version , it is able to do it. So, I advice you to run the new version of RhoTermPredict giving as input the previous file containing the 20 sequences. Results should be different from the previous ones.
