### ISSUE TITLE
High-throughput savvy implementation

### ISSUE THREAD

**Issue by oschwengers** [MarcoDiSalvo90/RhoTermPredict#3]
Hi @MarcoDiSalvo90 , thank you very much for this implementation of your promising algorithm published (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2704-x).

I'd be interested in using / integrate your tool / code in(to) some of our pipelines, however there are some issues which make it currently impossible to do this:

1. `AGPL` is a too strict license. Could you change this to `GPL3` or even `MIT` or maybe give a personal allowance to reuse this code?
2. There are some code quality issues not meeting common best practices, e.g. :
- spaces in file names (python script and output files)
- usage of Excel as output file format: this could easily be rewritten to use `tsv`
- not severe but yet not `PEP8` conform
3. The list or dependencies seems very long which I cannot comprehend from your python code which only imports `BioPython`, `Matplotlib` and `OpenPyXL`.

If these (and maybe other) issues would be resolved this code could be transformed into a proper Python tool and ported to `Bioconda` and thus easily be used for bacterial genome annotations.
Cheers and best regards!

**Comment by MarcoDiSalvo90** [comment]
Hi @oschwengers , thank you for your interest in my algorithm! I really appreciated your interest and your suggestions, but actually I'm already working to resolve the previous issues, both for RhoTermPredict and for other my algorithms,  in order to transform them into Python tools, as you said me. During the last year I could not do this for various reasons but now it is possible for me. RhoTermPredict is one of algorithms made during my PhD thesis and I can't wait to finish my work

best regards!!

**Comment by oschwengers** [comment]
Hi @MarcoDiSalvo90 , I'm glad to here that you're still working on and maintaining this project! If possible, I'd love to see the aforementioned issues being addressed, especially the removal of Excel files as output is sort of a no-go in high-throughput analysis - a simple `tsv` output file (start, stop, strand, etc. ) would be perfect.

And a port to `BioConda` would be very helpful. Let me know If I can help out somehow.

Thanks and best regards!

**Comment by MarcoDiSalvo90** [comment]
Sure @oschwengers, all your suggestions, that are very appreciated, will be considered!

Thanks and best regards!
